Repository aindo-com/aindo-anonymize, pull requests merged in 2025-04, with the labels that each got.

#8 feat: method `to_dict` for config classes
  src/aindo/anonymize/config.py
  src/aindo/anonymize/techniques/mocking.py
  tests/anonymize/test_config.py
Labels: feature

#9 ci: ensure documentation builds successfully on PRs and manual runs
  .github/workflows/main-ci-flow.yml
Labels: ci

#5 chore(main): release 1.1.0
  CHANGELOG.md
  src/aindo/anonymize/version.py
Labels: autorelease: pending

#11 docs: clarify that the process is "pseudonymisation"
  README.md
  docs/index.md
  pyproject.toml
Labels: documentation

#12 chore(main): release 1.1.1
  CHANGELOG.md
  src/aindo/anonymize/version.py
Labels: autorelease: pending
